version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - laravel
      - postgres
    networks:
      - laravel
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel
    environment:
      POSTGRES_DB: forge
  laravel:
    build:
      context: .
      dockerfile: laravel.dockerfile
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/forge
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:PoStwuoIPBnH+W2znwpmQbZvCJZPdou1DedUu+3F7mI=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
    ports:
      - "9000:9000"
    networks:
      - laravel
volumes:
  db_data:
